import { FileBarChart, FileText, Users, Building2, CalendarCheck, ShieldCheck, Download } from "lucide-react";
import { requirePermission } from "@/lib/session";
import { can } from "@/lib/permissions";
import { listReports } from "@/features/reports/queries";
import { generateReport } from "@/features/reports/actions";
import { parsePageParam } from "@/lib/utils";
import { Card, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, THead, TH, TBody, TR, TD, EmptyRow } from "@/components/ui/table";
import { Pagination } from "@/components/ui/pagination";
import { GenerateReportForm } from "@/features/reports/generate-report-form";
import type { Report } from "@prisma/client";

type ReportRow = Report & { generatedBy: { name: string } };

const REPORT_TYPE_LABELS: Record<string, string> = {
  EMPLOYEE_DIRECTORY: "Employee Directory",
  ATTENDANCE_SUMMARY: "Attendance Summary",
  COOPERATIVE_LISTING: "Cooperative Listing",
  HEADCOUNT: "Headcount",
  AUDIT_LOG: "Audit Log",
};

const REPORT_TYPE_ICONS: Record<string, typeof FileText> = {
  EMPLOYEE_DIRECTORY: Users,
  ATTENDANCE_SUMMARY: CalendarCheck,
  COOPERATIVE_LISTING: Building2,
  HEADCOUNT: Users,
  AUDIT_LOG: ShieldCheck,
};

export default async function ReportsPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const session = await requirePermission("VIEW_REPORTS");
  const canGenerate = can(session.user.role, "GENERATE_REPORTS");

  const params = await searchParams;
  const page = parsePageParam(params.page);

  const { items, total, totalPages } = await listReports(page);

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div>
        <h2 className="font-display text-xl font-semibold text-ink-900">Reports</h2>
        <p className="mt-1 text-sm text-ink-900/60">
          Generate and view system reports for employees, attendance, cooperatives, and more.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        {/* ── Generate report panel ─────────────────────────────────────── */}
        {canGenerate && (
          <div className="lg:col-span-1">
            <Card className="p-6">
              <div className="mb-5 flex items-center gap-2.5 border-b border-ink-900/8 pb-4">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-50 text-brand-700">
                  <FileBarChart className="h-4 w-4" />
                </div>
                <h3 className="font-display text-base font-semibold text-ink-900">Generate Report</h3>
              </div>
              <GenerateReportForm action={generateReport} />
            </Card>
          </div>
        )}

        {/* ── Report history ────────────────────────────────────────────── */}
        <div className={canGenerate ? "lg:col-span-2" : "lg:col-span-3"}>
          <Card>
            <CardHeader
              title="Report History"
              description={`${total} report${total === 1 ? "" : "s"} generated so far.`}
            />
            <Table>
              <THead>
                <TH>Report</TH>
                <TH>Format</TH>
                <TH>Generated by</TH>
                <TH>Date</TH>
                <TH className="text-right">File</TH>
              </THead>
              <TBody>
                {items.length === 0 && (
                  <EmptyRow colSpan={5}>
                    <FileBarChart className="mx-auto mb-2 h-8 w-8 text-ink-900/20" />
                    No reports have been generated yet.
                  </EmptyRow>
                )}
                {items.map((report: ReportRow) => {
                  const Icon = REPORT_TYPE_ICONS[report.type] ?? FileText;
                  return (
                    <TR key={report.id}>
                      <TD>
                        <div className="flex items-center gap-2.5">
                          <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-brand-50 text-brand-700">
                            <Icon className="h-4 w-4" />
                          </div>
                          <div>
                            <p className="font-medium text-ink-900">{report.title}</p>
                            <p className="text-xs text-ink-900/50">
                              {REPORT_TYPE_LABELS[report.type] ?? report.type}
                            </p>
                          </div>
                        </div>
                      </TD>
                      <TD>
                        <Badge tone={report.format === "PDF" ? "brand" : "neutral"}>
                          {report.format}
                        </Badge>
                      </TD>
                      <TD>{report.generatedBy.name}</TD>
                      <TD>
                        {new Date(report.createdAt).toLocaleDateString("en-US", {
                          year: "numeric",
                          month: "short",
                          day: "numeric",
                          hour: "2-digit",
                          minute: "2-digit",
                        })}
                      </TD>
                      <TD className="text-right">
                        {report.fileUrl ? (
                          <a
                            href={report.fileUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-1.5 text-sm font-medium text-brand-700 hover:underline"
                          >
                            <Download className="h-3.5 w-3.5" />
                            Download
                          </a>
                        ) : (
                          <span className="text-xs text-ink-900/40">—</span>
                        )}
                      </TD>
                    </TR>
                  );
                })}
              </TBody>
            </Table>

            <Pagination
              basePath="/reports"
              params={{}}
              page={page}
              totalPages={totalPages}
              totalItems={total}
              pageSize={10}
            />
          </Card>
        </div>
      </div>
    </div>
  );
}