/**
 * One-time script: remove all demo/seed data while preserving the real
 * org structure (departments, positions) and any real production records.
 *
 * Usage:
 *   npx tsx scripts/clean-demo-data.ts
 *
 * Targets only known demo records by their seeded employeeId/username/
 * cooperativeId — does NOT truncate any table.
 */

import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config();

import prisma from "../lib/prisma";

const DEMO_EMPLOYEE_CODES = ["EMP-0001","EMP-0002","EMP-0003","EMP-0004","EMP-0005","EMP-0006"];
const DEMO_USERNAMES      = ["admin","hr.officer","manager","amina.hussein"];
const DEMO_COOP_CODES     = ["COOP-001","COOP-002"];

async function main() {
  console.log("🔍 Scanning for demo records...\n");

  // ── Locate demo records ───────────────────────────────────────────────────

  const demoUsers = await prisma.user.findMany({
    where: { username: { in: DEMO_USERNAMES } },
    select: { id: true, name: true, username: true, role: true },
  });
  const demoUserIds = demoUsers.map((u) => u.id);

  const demoEmployees = await prisma.employee.findMany({
    where: { employeeId: { in: DEMO_EMPLOYEE_CODES } },
    select: { id: true, employeeId: true, firstName: true, lastName: true },
  });
  const demoEmployeeIds = demoEmployees.map((e) => e.id);

  const demoCoops = await prisma.cooperative.findMany({
    where: { cooperativeId: { in: DEMO_COOP_CODES } },
    select: { id: true, cooperativeId: true, name: true },
  });
  const demoCoopIds = demoCoops.map((c) => c.id);

  // ── Summary ───────────────────────────────────────────────────────────────

  console.log(`Demo users (${demoUsers.length}):`);
  demoUsers.forEach((u) => console.log(`  @${u.username}  ${u.name}  [${u.role}]`));

  console.log(`\nDemo employees (${demoEmployees.length}):`);
  demoEmployees.forEach((e) => console.log(`  ${e.employeeId}  ${e.firstName} ${e.lastName}`));

  console.log(`\nDemo cooperatives (${demoCoops.length}):`);
  demoCoops.forEach((c) => console.log(`  ${c.cooperativeId}  ${c.name}`));

  if (!demoUsers.length && !demoEmployees.length && !demoCoops.length) {
    console.log("\n✅ No demo data found. Database is already clean.");
    return;
  }

  console.log("\n🗑  Deleting demo data in FK-safe order...\n");

  // 1. Notifications for demo users
  if (demoUserIds.length) {
    const r = await prisma.notification.deleteMany({ where: { userId: { in: demoUserIds } } });
    console.log(`  notifications          : ${r.count} deleted`);
  }

  // 2. Sessions / accounts for demo users (Better Auth tables)
  if (demoUserIds.length) {
    const s = await prisma.session.deleteMany({ where: { userId: { in: demoUserIds } } });
    console.log(`  sessions               : ${s.count} deleted`);
    const a = await prisma.account.deleteMany({ where: { userId: { in: demoUserIds } } });
    console.log(`  auth accounts          : ${a.count} deleted`);
  }

  // 3. Audit logs written by demo users
  if (demoUserIds.length) {
    const r = await prisma.auditLog.deleteMany({ where: { userId: { in: demoUserIds } } });
    console.log(`  audit logs (by user)   : ${r.count} deleted`);
  }

  // 4. Reports generated by demo users
  if (demoUserIds.length) {
    const r = await prisma.report.deleteMany({ where: { generatedById: { in: demoUserIds } } });
    console.log(`  reports                : ${r.count} deleted`);
  }

  // 5. Leave requests for demo employees
  if (demoEmployeeIds.length) {
    const r = await prisma.leaveRequest.deleteMany({ where: { employeeId: { in: demoEmployeeIds } } });
    console.log(`  leave requests         : ${r.count} deleted`);
  }

  // 6. Attendance for demo employees
  if (demoEmployeeIds.length) {
    const r = await prisma.attendance.deleteMany({ where: { employeeId: { in: demoEmployeeIds } } });
    console.log(`  attendance records     : ${r.count} deleted`);
  }

  // 7. Documents for demo employees
  if (demoEmployeeIds.length) {
    const r = await prisma.document.deleteMany({ where: { employeeId: { in: demoEmployeeIds } } });
    console.log(`  documents              : ${r.count} deleted`);
  }

  // 8. Contracts for demo employees
  if (demoEmployeeIds.length) {
    const r = await prisma.contract.deleteMany({ where: { employeeId: { in: demoEmployeeIds } } });
    console.log(`  contracts              : ${r.count} deleted`);
  }

  // 9. Employment history for demo employees
  if (demoEmployeeIds.length) {
    const r = await prisma.employmentHistory.deleteMany({ where: { employeeId: { in: demoEmployeeIds } } });
    console.log(`  employment history     : ${r.count} deleted`);
  }

  // 10. Clear managerId references TO demo employees (prevent FK violation)
  if (demoEmployeeIds.length) {
    const r = await prisma.employee.updateMany({
      where: { managerId: { in: demoEmployeeIds } },
      data: { managerId: null },
    });
    console.log(`  manager refs cleared   : ${r.count} employees`);
  }

  // 11. Delete demo employees (unlink userId first to avoid unique constraint)
  if (demoEmployeeIds.length) {
    await prisma.employee.updateMany({
      where: { id: { in: demoEmployeeIds } },
      data: { userId: null },
    });
    const r = await prisma.employee.deleteMany({ where: { id: { in: demoEmployeeIds } } });
    console.log(`  employees              : ${r.count} deleted`);
  }

  // 12. Delete demo user records
  if (demoUserIds.length) {
    const r = await prisma.user.deleteMany({ where: { id: { in: demoUserIds } } });
    console.log(`  users                  : ${r.count} deleted`);
  }

  // 13. Delete demo cooperatives
  if (demoCoopIds.length) {
    const r = await prisma.cooperative.deleteMany({ where: { id: { in: demoCoopIds } } });
    console.log(`  cooperatives           : ${r.count} deleted`);
  }

  console.log("\n✅ Demo data removed successfully.");
  console.log("   Departments, positions, and any real user/employee records are untouched.");
}

main()
  .catch((e) => { console.error("❌", e); process.exit(1); })
  .finally(() => prisma.$disconnect());
